stages:
  - lint

lint_fix_job:
  stage: lint
  image: node:18
  script:
    - npm ci
    - npm run lint:fix
    - npm run lint  
  artifacts:
    paths:
      - src/               
    expire_in: 1 hour
